### ISSUE TITLE
Get Admin Access to Meetup

### ISSUE THREAD

**Issue by michaelachrisco** [freecodecamp-fresnoca/EventPlanning#1]
Give either @michaelachrisco and/or @ThomastheBicyclist admin access.

**Comment by ThomastheBicyclist** [comment]
Rick needs to do this: 
https://help.meetup.com/hc/en-us/articles/360002882191-How-do-I-step-down-as-organizer-

Otherwise we'll have to look at other ways to manage meetups.

**Comment by ThomastheBicyclist** [comment]
I sent him another email and a text message just now.

**Comment by michaelachrisco** [comment]
@ThomastheBicyclist  Its good. @rxsharp has given me admin access. Meetup is ~~forcing~~ asking us for 15$ a month 
![screenshot from 2018-07-07 20-10-20](https://user-images.githubusercontent.com/398491/42416398-d782efd2-8221-11e8-8d64-b33529f3f338.png)

Ill take a closer look tomorrow and get this sorted out.

**Comment by michaelachrisco** [comment]
Done. It turns out the 15 a month is for the first 6 months. Its 20$ a month otherwise....Kinda sucks but I paid for the next 6 months. So heres whats going to happen:

1. Either we get donations to keep ourselves on Meetup OR
2. We move to another platform that will not change us for the service.

I would love to keep using Meetup, but I dont feel the platform is worth 20 a month. Just my take on it.
