### ISSUE TITLE
Decide on Meetup (Donations/move off)

### ISSUE THREAD

**Issue by michaelachrisco** [freecodecamp-fresnoca/EventPlanning#4]
Either we get donations to keep ourselves on Meetup OR We move to another platform that will not change us for the service.

We will need another $20 (or 15 a month for 6 months around 90) in donations in order to keep ourselves on Meetup after Jan 2019.

**Comment by ThomastheBicyclist** [comment]
How about we build our own site as the primary source of information about the group (as well as a kind of live showcase of members’ work), use social media to share updates, and transition off of meetup.com?

**Comment by michaelachrisco** [comment]
Sounds good to me. We do need to look at all the overall options available for us.

**Comment by michaelachrisco** [comment]
@ThomastheBicyclist Ill be over at the hackerspace this Saturday if we would like to go over the specifics of the site.

**Comment by ThomastheBicyclist** [comment]
@michaelachrisco Sweet! I can be there in the late morning and/or after 4pm.
